# Generated by Django 5.0.2 on 2026-03-10 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='en_proceso', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='medio_pago',
            field=models.CharField(blank=True, choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('efectivo', 'Efectivo'), ('otros', 'Otros')], max_length=20, null=True, verbose_name='Medio de Pago'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='monto_establecimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Establecimiento'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='monto_estilista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Estilista'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='tipo_reparto_establecimiento',
            field=models.CharField(blank=True, choices=[('porcentaje', 'Porcentaje'), ('monto', 'Monto Fijo')], max_length=20, null=True, verbose_name='Tipo Reparto Establecimiento'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='valor_reparto_establecimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Reparto Establecimiento'),
        ),
        migrations.AlterField(
            model_name='serviciorealizado',
            name='precio_cobrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Cobrado'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_realizados', to='api.cliente', verbose_name='Cliente'),
        ),
    ]
