# Generated by Django 5.0.2 on 2026-03-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_serviciorealizado_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('recepcionista', 'Recepcionista'), ('empleado', 'Empleado'), ('visualizador', 'Visualizador')], default='empleado', max_length=20, verbose_name='Rol'),
        ),
    ]
