# Generated by Django 5.0.2 on 2026-03-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comision_estilista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión Estilista (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Presentación'),
        ),
    ]
