# Generated by Django 5.0.2 on 2026-03-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_producto_comision_estilista_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizado',
            name='factura_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Factura'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Número Factura'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Cliente'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='factura_texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Factura'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='medio_pago',
            field=models.CharField(choices=[('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('efectivo', 'Efectivo'), ('otros', 'Otros')], default='efectivo', max_length=20, verbose_name='Medio de Pago'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Número Factura'),
        ),
    ]
