# Generated by Django 5.0.2 on 2026-03-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_serviciorealizado_factura_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilista',
            name='tipo_cobro_espacio',
            field=models.CharField(choices=[('ninguno', 'Sin Cobro'), ('alquiler', 'Alquiler Fijo'), ('comision', 'Comisión sobre Ganancias')], default='ninguno', max_length=20, verbose_name='Tipo Cobro Espacio'),
        ),
        migrations.AddField(
            model_name='estilista',
            name='valor_cobro_espacio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Cobro Espacio'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='estilista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_productos', to='api.estilista', verbose_name='Estilista'),
        ),
    ]
