# Generated by Django 5.0.2 on 2026-03-13

import django.db.models.deletion
from django.db import migrations, models


def normalizar_roles_y_cobros(apps, schema_editor):
    Usuario = apps.get_model('api', 'Usuario')
    Estilista = apps.get_model('api', 'Estilista')

    Usuario.objects.filter(rol='recepcionista').update(rol='recepcion')
    Usuario.objects.filter(rol='empleado').update(rol='recepcion')
    Usuario.objects.filter(rol='visualizador').update(rol='recepcion')

    Estilista.objects.filter(tipo_cobro_espacio='ninguno').update(tipo_cobro_espacio='sin_cobro')
    Estilista.objects.filter(tipo_cobro_espacio='comision').update(tipo_cobro_espacio='porcentaje_neto')
    Estilista.objects.filter(tipo_cobro_espacio='alquiler').update(tipo_cobro_espacio='costo_fijo_neto')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_estilista_tipo_cobro_espacio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(
                choices=[
                    ('administrador', 'Administrador'),
                    ('gerente', 'Gerente'),
                    ('recepcion', 'Recepción'),
                ],
                default='recepcion',
                max_length=20,
                verbose_name='Rol',
            ),
        ),
        migrations.AlterField(
            model_name='estilista',
            name='tipo_cobro_espacio',
            field=models.CharField(
                choices=[
                    ('sin_cobro', 'Sin cobro (100% empleado)'),
                    ('porcentaje_neto', '% sobre neto del empleado'),
                    ('costo_fijo_neto', 'Costo fijo sobre neto del empleado'),
                ],
                default='sin_cobro',
                max_length=20,
                verbose_name='Tipo Cobro Espacio',
            ),
        ),
        migrations.AddField(
            model_name='estilista',
            name='comision_ventas_productos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión Ventas Productos (%)'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='adicional_guantes',
            field=models.BooleanField(default=False, verbose_name='Adicional Guantes'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='adicional_otro_cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad Adicional Otro'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='adicional_otro_producto',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='servicios_adicionales',
                to='api.producto',
                verbose_name='Adicional Otro Producto',
            ),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='adicional_shampoo',
            field=models.BooleanField(default=False, verbose_name='Adicional Shampoo'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='neto_servicio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Neto Servicio'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='tiene_adicionales',
            field=models.BooleanField(default=False, verbose_name='Tiene Adicionales'),
        ),
        migrations.AddField(
            model_name='serviciorealizado',
            name='valor_adicionales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Adicionales'),
        ),
        migrations.RunPython(normalizar_roles_y_cobros, migrations.RunPython.noop),
    ]
