# Generated by Django 5.0.2 on 2026-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_estadopagoestilistadia_pagos_por_medio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estilista',
            options={'ordering': ['nombre'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='neto_dia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Neto del día'),
        ),
        migrations.AlterField(
            model_name='estilista',
            name='tipo_cobro_espacio',
            field=models.CharField(choices=[('sin_cobro', 'Sin cobro (100% empleado)'), ('porcentaje_neto', '% sobre neto del empleado'), ('costo_fijo_neto', 'Costo fijo sobre neto del empleado')], default='ninguno', max_length=20, verbose_name='Tipo Cobro Espacio'),
        ),
    ]
