# Generated by Django 5.0.2 on 2026-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_estadopagoestilistahistorial_abono_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='abono_puesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abono puesto'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='pendiente_puesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Pendiente puesto'),
        ),
    ]
