# Generated by Django 5.0.2 on 2026-03-25 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_estadopagoestilistadia_abono_puesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='descuento_puesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento por alquiler puesto/espacio'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='ganancias_totales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancias totales (servicios + comisiones)'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='saldo_puesto_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo pendiente del puesto después de pago'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='total_pagable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total pagable (ganancias - descuento puesto)'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='usuario_liquida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la liquidación'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='abono_puesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Abono realizado al puesto'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('cancelado', 'Pagado/Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del día'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='neto_dia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Neto del día (DEPRECATED)'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='pendiente_puesto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Pendiente puesto (DEPRECATED)'),
        ),
    ]
