# Generated by Django 5.0.2 on 2026-03-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_recreate_estado_pago_estilista_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('debe', 'Con deuda del puesto'), ('cancelado', 'Pagado/Cancelado')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
