# Generated by Django 5.0.2 on 2026-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_estadopagoestilistadia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadopagoestilistahistorial',
            name='estado_anterior',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('debe', 'Debe'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado Anterior'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistahistorial',
            name='estado_nuevo',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('debe', 'Debe'), ('cancelado', 'Cancelado')], max_length=20, verbose_name='Estado Nuevo'),
        ),
    ]
