# Generated by Django 6.0.6 on 2026-06-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_saldodeudapuesto_saldo_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='medio_abono_puesto',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otros', 'Otros')], default='efectivo', max_length=20, verbose_name='Medio de pago abono puesto'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistahistorial',
            name='medio_abono_puesto',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otros', 'Otros')], default='efectivo', max_length=20, verbose_name='Medio abono puesto'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='skip_descuento_puesto',
            field=models.BooleanField(default=False, help_text='Si es True, ese día NO se descuenta puesto del pago. El descuento se suma a la deuda.', verbose_name='Omitir descuento de puesto'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='total_pagable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total pagable al empleado'),
        ),
    ]
