# Generated by Django 6.0.6 on 2026-07-18 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_create_creditos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('credito_creado', 'Crédito creado'), ('credito_editado', 'Crédito editado'), ('credito_cancelado', 'Crédito cancelado'), ('credito_eliminado', 'Crédito eliminado'), ('abono_creado', 'Abono registrado'), ('abono_editado', 'Abono editado'), ('abono_eliminado', 'Abono eliminado')], max_length=30, verbose_name='Acción')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Historial de crédito',
                'verbose_name_plural': 'Historial de créditos',
                'db_table': 'creditos_historial',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RenameIndex(
            model_name='abonocredito',
            new_name='abonos_cred_credito_5dc456_idx',
            old_name='ix_abono_credito_fecha',
        ),
        migrations.RenameIndex(
            model_name='credito',
            new_name='creditos_estilis_8d3e82_idx',
            old_name='ix_credito_est_fecha',
        ),
        migrations.RenameIndex(
            model_name='credito',
            new_name='creditos_estado_7a63f7_idx',
            old_name='ix_credito_estado_fecha',
        ),
        migrations.RenameIndex(
            model_name='credito',
            new_name='creditos_fecha_v_03de0f_idx',
            old_name='ix_credito_vencimiento',
        ),
        migrations.AddField(
            model_name='credito',
            name='usuario_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_editados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que modificó el crédito'),
        ),
        migrations.AddField(
            model_name='creditohistorial',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='api.credito', verbose_name='Crédito'),
        ),
        migrations.AddField(
            model_name='creditohistorial',
            name='estilista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_creditos', to='api.estilista', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='creditohistorial',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_creditos_generado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='creditohistorial',
            index=models.Index(fields=['estilista', '-fecha'], name='creditos_hi_estilis_fe697f_idx'),
        ),
        migrations.AddIndex(
            model_name='creditohistorial',
            index=models.Index(fields=['credito', '-fecha'], name='creditos_hi_credito_adde71_idx'),
        ),
    ]
