# Generated by Django 5.0.2 on 2026-07-31 01:07

import inspect

import django.db.models.deletion
from django.db import migrations, models

# El kwarg de CheckConstraint para la condición cambió de nombre entre
# versiones de Django ("check" en versiones viejas, "condition" en nuevas).
# Se detecta en tiempo de import para que esta migración corra igual en
# cualquiera de los dos.
_CHECK_CONSTRAINT_KWARG = (
    'condition' if 'condition' in inspect.signature(models.CheckConstraint.__init__).parameters else 'check'
)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_creditohistorial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('documento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Documento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Persona con crédito',
                'verbose_name_plural': 'Personas con crédito',
                'db_table': 'personas_credito',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='credito',
            name='estilista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='api.estilista', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='creditohistorial',
            name='estilista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_creditos', to='api.estilista', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='credito',
            name='persona_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='api.personacredito', verbose_name='Persona externa'),
        ),
        migrations.AddField(
            model_name='creditohistorial',
            name='persona_credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial_creditos', to='api.personacredito', verbose_name='Persona externa'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['persona_credito', '-fecha_creacion'], name='creditos_persona_57614f_idx'),
        ),
        migrations.AddIndex(
            model_name='creditohistorial',
            index=models.Index(fields=['persona_credito', '-fecha'], name='creditos_hi_persona_d7639d_idx'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(**{_CHECK_CONSTRAINT_KWARG: models.Q(models.Q(('estilista__isnull', False), ('persona_credito__isnull', True)), models.Q(('estilista__isnull', True), ('persona_credito__isnull', False)), _connector='OR')}, name='credito_titular_unico'),
        ),
    ]
