# Generated by Django 5.0.2 on 2026-07-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_personacredito_alter_credito_estilista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='comision_producto_dia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='No es efectivo físico en mano del empleado (ya entró a caja al vender el producto); solo sirve para cubrir deducciones.', max_digits=12, verbose_name='Comisión por venta/consumo de producto del día'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='descuento_consumo_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deuda de consumo aplicada/cobrada ese día'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='ganancia_efectivo_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancia del día pagada en efectivo (dinero real en caja)'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='ganancia_electronica_daviplata',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancia electrónica Daviplata'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='ganancia_electronica_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancia del día pagada por medio electrónico (informativo, ya en manos del empleado)'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='ganancia_electronica_nequi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancia electrónica Nequi'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='ganancia_electronica_otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ganancia electrónica otros'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='monto_pagar_entregado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto ya confirmado entregado al empleado'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='monto_pagar_establecimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto que el negocio debe entregar en efectivo al empleado (sobrante tras deducciones)'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='monto_transferir_empleado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto que el empleado debe transferir (si el efectivo no alcanzó para cubrir deducciones)'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='monto_transferir_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto ya confirmado recibido de la transferencia del empleado'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='motor_calculo',
            field=models.CharField(default='v2_mixed', help_text="'v2_mixed' (legacy, Nequi/Daviplata entraban a caja) o 'v3_efectivo' (solo efectivo).", max_length=20, verbose_name='Motor de cálculo usado'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='reparto_establecimiento_electronico_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Se suma a las deducciones del día (el negocio siempre recupera su parte).', max_digits=12, verbose_name='% de establecimiento de servicios pagados electrónico, pendiente de recuperar'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='saltar_descuento_consumo',
            field=models.BooleanField(default=False, help_text='Análogo a skip_descuento_puesto pero para la deuda de consumo de productos del empleado.', verbose_name='Omitir descuento de consumo'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='total_deducciones_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total deducciones del día (puesto + consumo + reparto electrónico pendiente)'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistahistorial',
            name='descuento_consumo_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento consumo del día'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistahistorial',
            name='monto_pagar_establecimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto a pagar por el establecimiento'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistahistorial',
            name='monto_transferir_empleado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto a transferir por el empleado'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistahistorial',
            name='motor_calculo',
            field=models.CharField(default='v2_mixed', max_length=20, verbose_name='Motor de cálculo usado'),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='ganancia_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='ganancia_electronica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='ganancia_electronica_daviplata',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='ganancia_electronica_nequi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='ganancia_electronica_otros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='monto_pagar_entregado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='monto_pagar_establecimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='monto_transferir_empleado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='monto_transferir_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='reparto_establecimiento_electronico_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='saltar_descuento_consumo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='total_deducciones_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
