# Generated by Django 5.0.2 on 2026-07-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_estadopagoestilistadia_comision_producto_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estilista',
            name='datos_transferencia',
            field=models.TextField(blank=True, help_text='Banco, número de cuenta, titular -- para cuando el cliente prefiere transferir en vez de escanear.', null=True, verbose_name='Datos de transferencia'),
        ),
        migrations.AddField(
            model_name='estilista',
            name='qr_daviplata',
            field=models.ImageField(blank=True, null=True, upload_to='qr_empleados/daviplata/', verbose_name='QR Daviplata'),
        ),
        migrations.AddField(
            model_name='estilista',
            name='qr_nequi',
            field=models.ImageField(blank=True, null=True, upload_to='qr_empleados/nequi/', verbose_name='QR Nequi'),
        ),
        migrations.AddField(
            model_name='estilista',
            name='qr_otros',
            field=models.ImageField(blank=True, null=True, upload_to='qr_empleados/otros/', verbose_name='QR otro medio'),
        ),
    ]
