# Generated by Django 5.0.2 on 2026-07-31 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_estilista_datos_transferencia_estilista_qr_daviplata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciorealizado',
            name='cobrado_por',
            field=models.ForeignKey(blank=True, help_text='Empleado que efectivamente recibió el pago electrónico de este servicio, si fue distinto al que lo realizó (servicios cobrados en conjunto).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_cobrados_de_companeros', to='api.estilista', verbose_name='Cobrado por (si fue otro empleado)'),
        ),
        migrations.CreateModel(
            name='DeudaEntreEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('monto_abonado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto abonado')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo pendiente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('acreedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_entre_empleados_le_deben', to='api.estilista', verbose_name='Empleado al que se le debe')),
                ('deudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_entre_empleados_debe', to='api.estilista', verbose_name='Empleado que cobró (debe)')),
                ('servicio_realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_entre_empleados', to='api.serviciorealizado', verbose_name='Servicio de origen')),
            ],
            options={
                'verbose_name': 'Deuda entre empleados',
                'verbose_name_plural': 'Deudas entre empleados',
                'db_table': 'deudas_entre_empleados',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AbonoDeudaEntreEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto abonado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha del abono')),
                ('notas', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abonos_deuda_entre_empleados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró el abono')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='api.deudaentreempleados', verbose_name='Deuda')),
            ],
            options={
                'verbose_name': 'Abono deuda entre empleados',
                'verbose_name_plural': 'Abonos deuda entre empleados',
                'db_table': 'abonos_deuda_entre_empleados',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='deudaentreempleados',
            index=models.Index(fields=['deudor', 'estado'], name='deudas_entr_deudor__201e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='deudaentreempleados',
            index=models.Index(fields=['acreedor', 'estado'], name='deudas_entr_acreedo_2b89d4_idx'),
        ),
    ]
