# Generated by Django 6.0.6 on 2026-07-31 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_serviciorealizado_cobrado_por_deudaentreempleados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonodeudaempleado',
            name='origen_liquidacion_fecha',
            field=models.DateField(blank=True, help_text='Fecha operativa de la liquidación (solo efectivo) que aplicó este abono automáticamente, para poder revertirlo si se elimina esa liquidación.', null=True, verbose_name='Fecha de la liquidación que generó este abono'),
        ),
    ]
