# Generated by Django 6.0.6 on 2026-08-11 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_abono_deuda_empleado_origen_liquidacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deudaentreempleados',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Vale entre empleados', 'verbose_name_plural': 'Vales entre empleados'},
        ),
        migrations.AddField(
            model_name='abonodeudaentreempleados',
            name='origen_liquidacion_fecha',
            field=models.DateField(blank=True, help_text='Fecha operativa de la liquidación (solo efectivo) que aplicó este abono automáticamente al descontar el Vale, para poder revertirlo si se elimina esa liquidación.', null=True, verbose_name='Fecha de la liquidación que generó este abono'),
        ),
        migrations.AddField(
            model_name='deudaentreempleados',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Vale (registro manual)'),
        ),
        migrations.AddField(
            model_name='deudaentreempleados',
            name='notas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='descuento_vale_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vale (deuda entre empleados) aplicado/cobrado ese día'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistadia',
            name='skip_descuento_vale',
            field=models.BooleanField(default=False, help_text='Análogo a skip_descuento_puesto pero para el Vale (deuda entre empleados). Si es True, ese día no se descuenta y el Vale queda pendiente para otro día.', verbose_name='Omitir descuento de Vale'),
        ),
        migrations.AddField(
            model_name='estadopagoestilistahistorial',
            name='descuento_vale_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vale (deuda entre empleados) aplicado del día'),
        ),
        migrations.AddField(
            model_name='factliquidacionestilistadia',
            name='descuento_vale_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='saldodeudapuesto',
            name='saldo_vale',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de los Vales pendientes donde este empleado es el deudor (cobró de más).', max_digits=12, verbose_name='Saldo acumulado de Vale (debe a compañeros)'),
        ),
        migrations.AlterField(
            model_name='deudaentreempleados',
            name='deudor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas_entre_empleados_debe', to='api.estilista', verbose_name='Empleado que cobró de más (debe)'),
        ),
        migrations.AlterField(
            model_name='deudaentreempleados',
            name='servicio_realizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deudas_entre_empleados', to='api.serviciorealizado', verbose_name='Servicio de origen'),
        ),
        migrations.AlterField(
            model_name='estadopagoestilistadia',
            name='total_deducciones_dia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total deducciones del día (puesto + consumo + vale + reparto electrónico pendiente)'),
        ),
    ]
